name: OfflineMessenger
main: carrot.offlinemsg.OfflineMessenger
author: Carrot
version: 1.2.173
description: A plugin for sending messages to players when they join. Mail v2
softdepend: [PermissionsEx]

permissions:
  om.clearPlayer:
    description: Clear a player's messages
  om.sendPlayer:
    description: Send messages to a player next time they join
  om.showPlayer:
    description: Show the queued messages of other players

commands:
  offlinemessenger:
    usage: The main command for OfflineMessenger
    description: The main command for OfflineMessenger
    aliases: [om]
    default: true
